export interface MovilidadItem {
  titulo: string;
  descripcion: string;
  paises: string[];
  banderas: string[];
  etapa: string;
  participantes?: string;
  tipo: 'alumnado' | 'profesorado' | 'recepcion';
  fotos?: string[];
}

export interface ProyectoErasmus {
  curso: string;
  etiqueta: string;
  movilidades: MovilidadItem[];
}

export const acreditacion = {
  tipo: 'Acreditación Erasmus+ — Educación Escolar',
  desde: '2021',
  hasta: '2027',
  descripcion: 'El IES Jándula obtuvo la Acreditación Erasmus+ para el sector de Educación Escolar en el curso 2021-22, vigente hasta 2027. Esta acreditación garantiza la continuidad y calidad de nuestros proyectos de internacionalización.',
};

export const proyectosErasmus: ProyectoErasmus[] = [
  {
    curso: '2024-25',
    etiqueta: 'Acredita 24-25',
    movilidades: [
      {
        titulo: 'Movilidad a Tours — Patrimonio y Loira',
        descripcion: 'Alumnado viaja a la región del Loira trabajando sobre patrimonio y sostenibilidad con su centro socio francés. La experiencia incluye visitas culturales, actividades colaborativas y el enriquecedor contacto con familias locales. "El trabajo ha quedado fenomenal y los recuerdos durarán para siempre."',
        paises: ['Francia'],
        banderas: ['🇫🇷'],
        etapa: 'Bachillerato',
        participantes: '10 alumnos y 2 profesores',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/tours-2024.jpg'],
      },
      {
        titulo: 'Movilidad a Stolberg — Creciendo hacia un estilo de vida saludable',
        descripcion: 'Semana de aprendizaje conjunto con el Goethe Gymnasium (Alemania) y el Forssan Yhteislyseo (Finlandia) sobre hábitos saludables y sostenibilidad. Actividades: cultivo de setas, elaboración de crema de manos con cera de abeja, construcción de hoteles de insectos, visita al castillo de Stolberg, gymkhana por Colonia y excursión al Parque Nacional del Eifel.',
        paises: ['Alemania', 'Finlandia'],
        banderas: ['🇩🇪', '🇫🇮'],
        etapa: 'Bachillerato',
        participantes: 'Grupo de alumnos',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/stolberg-2024.jpg', '/images/erasmus/stolberg-actividades-finales.jpg'],
      },
      {
        titulo: 'Erasmus en Forssa — Castillos y parques naturales',
        descripcion: '9 alumnos de 2º de Bachillerato viajan a Forssa (Finlandia) dentro del proyecto sobre castillos y espacios naturales protegidos.',
        paises: ['Finlandia'],
        banderas: ['🇫🇮'],
        etapa: '2º Bachillerato',
        participantes: '9 alumnos',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/finlandia-2024.jpg'],
      },
      {
        titulo: 'Estancia de larga duración — Alumnado francés en Andújar',
        descripcion: 'Alumnos del Collège Georges Gironde (Segré-en-Anjou Bleu, Francia) realizan una estancia de larga duración integrados en las clases de 3º ESO del IES Jándula.',
        paises: ['Francia'],
        banderas: ['🇫🇷'],
        etapa: '3º ESO',
        participantes: 'Alumnado del Collège Georges Gironde',
        tipo: 'recepcion',
      },
      {
        titulo: 'Job shadowing — Liceo G. Berto (Italia)',
        descripcion: 'Recepción de una delegación docente del Liceo G. Berto de Vibo Valentia (Calabria, Italia) para observar las prácticas educativas del centro.',
        paises: ['Italia'],
        banderas: ['🇮🇹'],
        etapa: 'Profesorado',
        tipo: 'recepcion',
        fotos: ['/images/erasmus/vibo-valentia.jpg'],
      },
      {
        titulo: 'Job shadowing en Grecia',
        descripcion: 'La profesora Mercedes Casuso realiza una estancia de observación en Grecia, incluyendo actividades teatrales en el yacimiento arqueológico de Dodona.',
        paises: ['Grecia'],
        banderas: ['🇬🇷'],
        etapa: 'Profesorado',
        tipo: 'profesorado',
        fotos: ['/images/erasmus/grecia-erasmus-days.jpg'],
      },
    ],
  },
  {
    curso: '2023-24',
    etiqueta: 'Acredita 23-24',
    movilidades: [
      {
        titulo: 'Mens Sana in Corpore Sano — Semana internacional en Andújar',
        descripcion: 'Proyecto colaborativo con Francia, Alemania y España. El IES Jándula acoge a estudiantes del Collège de Pacé y del Goethe Gymnasium de Stolberg durante una intensa semana de actividades sobre salud, bienestar y sostenibilidad.',
        paises: ['Francia', 'Alemania', 'España'],
        banderas: ['🇫🇷', '🇩🇪'],
        etapa: 'ESO / Bachillerato',
        tipo: 'recepcion',
        fotos: ['/images/erasmus/mens-sana-andujar.jpg', '/images/erasmus/mens-sana-apertura.jpg'],
      },
      {
        titulo: 'Mens Sana in Corpore Sano — Movilidad a Pacé (Francia)',
        descripcion: 'Alumnado del IES Jándula viaja a Pacé (Bretaña, Francia) como parte del proyecto Mens Sana. Estancia de larga duración integrada en el Collège de Pacé con actividades sobre hábitos de vida saludable.',
        paises: ['Francia'],
        banderas: ['🇫🇷'],
        etapa: 'ESO / Bachillerato',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/pace-aeropuerto.jpg', '/images/erasmus/pace-larga-duracion.jpg'],
      },
      {
        titulo: 'Patrimonio y sostenibilidad — Tours (Francia)',
        descripcion: 'Movilidad a Tours en el marco de la colaboración con el Collège de la región del Loira, centrada en patrimonio histórico y sostenibilidad medioambiental.',
        paises: ['Francia'],
        banderas: ['🇫🇷'],
        etapa: 'ESO / Bachillerato',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/tours-23-24.jpg'],
      },
      {
        titulo: 'Tracing and Living Democracy — Stolberg, Alemania',
        descripcion: 'Proyecto cívico con el Goethe Gymnasium de Stolberg sobre la evolución democrática en España y Alemania. Incluye intercambio de visitas y recepción del alumnado alemán en Andújar.',
        paises: ['Alemania'],
        banderas: ['🇩🇪'],
        etapa: 'ESO / Bachillerato',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/tracing-democracy.jpg', '/images/erasmus/stolberg-recepcion-andujar.jpg'],
      },
      {
        titulo: 'Movilidades de larga duración — Colonia, Alemania',
        descripcion: 'Tres alumnas (Lucía, Violeta, Triana) realizan una estancia de un mes en Colonia integradas en el Maximilian Kolbe Gymnasium.',
        paises: ['Alemania'],
        banderas: ['🇩🇪'],
        etapa: 'ESO / Bachillerato',
        participantes: '3 alumnas',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/larga-duracion-colonia-1.jpg', '/images/erasmus/larga-duracion-colonia-2.jpg'],
      },
      {
        titulo: 'ForssAndújar — Finlandia',
        descripcion: '9 alumnos de 2º de Bachillerato viajan a Forssa (Finlandia) para el proyecto sobre sostenibilidad en centros educativos y parques naturales.',
        paises: ['Finlandia'],
        banderas: ['🇫🇮'],
        etapa: '2º Bachillerato',
        participantes: '9 alumnos',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/finlandia-2023.jpg', '/images/erasmus/visita-finlandia.jpg'],
      },
      {
        titulo: 'Job shadowing — Alemania y Francia',
        descripcion: 'Profesorado del IES Jándula realiza estancias de observación docente en centros educativos de Alemania y Francia.',
        paises: ['Alemania', 'Francia'],
        banderas: ['🇩🇪', '🇫🇷'],
        etapa: 'Profesorado',
        participantes: '4 profesores',
        tipo: 'profesorado',
      },
      {
        titulo: 'Job shadowing en Grecia — Dodona',
        descripcion: 'Las profesoras Mercedes Casuso y Matilde Morales (IES Al-Ándalus) realizan una estancia de observación en Grecia con visita al yacimiento arqueológico de Dodona.',
        paises: ['Grecia'],
        banderas: ['🇬🇷'],
        etapa: 'Profesorado',
        tipo: 'profesorado',
        fotos: ['/images/erasmus/jobshadowing-grecia.jpg', '/images/erasmus/grecia-nani-1.jpg', '/images/erasmus/grecia-nani-2.jpg'],
      },
    ],
  },
  {
    curso: '2022-23',
    etiqueta: 'Acredita 22-23',
    movilidades: [
      {
        titulo: 'Visita de alumnos franceses de Tours',
        descripcion: '14 estudiantes del Lycée Sainte-Ursule de Tours visitan el IES Jándula durante una semana de intercambio. Comparten actividades con alumnado de 4º ESO y conocen Andújar, Córdoba y Granada.',
        paises: ['Francia'],
        banderas: ['🇫🇷'],
        etapa: '4º ESO',
        participantes: '14 alumnos y 2 profesoras francesas',
        tipo: 'recepcion',
        fotos: ['/images/erasmus/tours-franceses-22-23.jpg'],
      },
      {
        titulo: 'SLOW — Lago de Garda, Italia',
        descripcion: 'Proyecto Erasmus-eTwinning "Sustainable Life – Outdoor Wellness" con movilidad a la región del Lago de Garda (Italia).',
        paises: ['Italia'],
        banderas: ['🇮🇹'],
        etapa: 'ESO / Bachillerato',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/slow-italia.jpg'],
      },
      {
        titulo: 'CAME SAW LIVED — Italia y España',
        descripcion: 'Viajamos con Julio César por Italia y España. Alumnado de Bachillerato y 3º ESO colabora con el IES Al-Ándalus (Almería) y estudiantes de Vibo Valentia (Italia). Debate final en Almería.',
        paises: ['Italia', 'España'],
        banderas: ['🇮🇹'],
        etapa: 'Bachillerato y 3º ESO',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/came-saw-lived.jpg'],
      },
      {
        titulo: 'ForssAndújar — Forssa, Finlandia',
        descripcion: 'Intercambio de visitas con el instituto finlandés de Forssa. El alumnado finlandés visita el Santuario de la Virgen de la Cabeza y los parques naturales de la zona.',
        paises: ['Finlandia'],
        banderas: ['🇫🇮'],
        etapa: 'ESO / Bachillerato',
        tipo: 'alumnado',
      },
      {
        titulo: 'Movilidades de larga duración — Colonia, Alemania',
        descripcion: '7 alumnos realizan una estancia de larga duración integrados en un instituto de Colonia.',
        paises: ['Alemania'],
        banderas: ['🇩🇪'],
        etapa: 'ESO / Bachillerato',
        participantes: '7 alumnos',
        tipo: 'alumnado',
        fotos: ['/images/erasmus/grupo-alemania-2022.jpg', '/images/erasmus/colonia-2022.jpg'],
      },
      {
        titulo: 'Job shadowing — Finlandia y Alemania',
        descripcion: '4 profesores realizan estancias de observación docente en Forssa (Finlandia) y Colonia (Alemania).',
        paises: ['Finlandia', 'Alemania'],
        banderas: ['🇫🇮', '🇩🇪'],
        etapa: 'Profesorado',
        participantes: '4 profesores',
        tipo: 'profesorado',
      },
    ],
  },
  {
    curso: '2021-22',
    etiqueta: 'Acredita 21-22',
    movilidades: [
      {
        titulo: 'Movilidad a Tours, Francia — Heritage joins our cultures',
        descripcion: 'Primera movilidad como centro acreditado. 17 alumnas de 4º ESO viajan a Tours (Francia) del 2 al 9 de abril de 2022 dentro del proyecto sobre patrimonio y culturas compartidas.',
        paises: ['Francia'],
        banderas: ['🇫🇷'],
        etapa: '4º ESO',
        participantes: '17 alumnas',
        tipo: 'alumnado',
      },
      {
        titulo: 'To a Greener Europe & CLOCK — Colonia, Alemania',
        descripcion: 'Dos movilidades simultáneas a Colonia en octubre de 2022 con el proyecto de sostenibilidad "A Greener Europe" y el proyecto "CLOCK – Sustainable Cities".',
        paises: ['Alemania'],
        banderas: ['🇩🇪'],
        etapa: 'ESO / Bachillerato',
        participantes: '3 alumnas y 1 profesora',
        tipo: 'alumnado',
      },
    ],
  },
];

export const movilidadesFP = [
  {
    programa: 'Talentum VI',
    curso: '2024-25',
    titulo: 'Prácticas en Italia — CFGM Guía en el Medio Natural',
    descripcion: 'Alumnado de 2º de CFGM de Guía en el Medio Natural y Tiempo Libre realiza su FFE en Italia a través del programa Talentum (Diputación de Jaén).',
    paises: ['Italia'],
    banderas: ['🇮🇹'],
    ciclo: 'CFGM Guía en el Medio Natural y Tiempo Libre',
    fotos: ['/images/erasmus/talentum-italia.jpg'],
  },
  {
    programa: 'Jaén+ VIII',
    curso: '2024-25',
    titulo: 'Prácticas en Italia y Portugal — CFGM',
    descripcion: '4 alumnos de 2º de CFGM realizan su FFE en empresas de Italia y Portugal a través del programa Jaén+ VIII (Diputación de Jaén).',
    paises: ['Italia', 'Portugal'],
    banderas: ['🇮🇹', '🇵🇹'],
    ciclo: 'CFGM',
    participantes: '4 alumnos',
    fotos: ['/images/erasmus/pace-aeropuerto.jpg'],
  },
  {
    programa: 'Talentum V',
    curso: '2023-24',
    titulo: 'Prácticas en Catania, Italia',
    descripcion: 'Juan Gil y Hugo Hervás, alumnos de 2º de CFGM de Guía en el Medio Natural, realizan tres meses de prácticas extracurriculares en Catania (Italia) gracias a Erasmus+.',
    paises: ['Italia'],
    banderas: ['🇮🇹'],
    ciclo: 'CFGM Guía en el Medio Natural y Tiempo Libre',
    participantes: 'Juan Gil y Hugo Hervás',
    fotos: [
      '/images/erasmus/talentum5-catania-1.jpg',
      '/images/erasmus/talentum5-catania-2.jpg',
      '/images/erasmus/talentum5-catania-3.jpg',
      '/images/erasmus/talentum5-catania-4.jpg',
      '/images/erasmus/talentum5-catania-5.jpg',
      '/images/erasmus/talentum5-vuelta-1.jpg',
      '/images/erasmus/talentum5-vuelta-2.jpg',
      '/images/erasmus/talentum5-vuelta-3.jpg',
      '/images/erasmus/talentum5-vuelta-4.jpg',
    ],
  },
  {
    programa: 'Jaén+ VII',
    curso: '2023-24',
    titulo: 'Prácticas en Grecia',
    descripcion: 'Luis Miguel Mudarra, alumno de 2º de CFGM de Guía en el Medio Natural, realiza su FFE en Grecia dentro del programa provincial Jaén+ VII.',
    paises: ['Grecia'],
    banderas: ['🇬🇷'],
    ciclo: 'CFGM Guía en el Medio Natural y Tiempo Libre',
    participantes: 'Luis Miguel Mudarra',
    fotos: [
      '/images/erasmus/jaen7-grecia-1.jpg',
      '/images/erasmus/jaen7-grecia-2.jpg',
      '/images/erasmus/jaen7-grecia-3.jpg',
      '/images/erasmus/jaen7-grecia-4.jpg',
      '/images/erasmus/jaen7-grecia-5.jpg',
      '/images/erasmus/jaen7-vuelta-1.jpg',
      '/images/erasmus/jaen7-vuelta-2.jpg',
      '/images/erasmus/jaen7-vuelta-3.jpg',
    ],
  },
];
